## docker-compose.production.yml
services:
  webapp:
    image: ${FRONTEND_RELEASE_IMAGE}
    ports:
      - "80:3000"
    env_file:
      - .env
    restart: always
  backend:
    image: ${BACKEND_RELEASE_IMAGE}
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
